# Generated by Django 4.1.7 on 2024-03-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_brand', '0001_initial'),
    ]

    operations = [
    ]
